//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    
    public partial class Music
    {
        public int Id { get; set; }

        [Required] public string Singer { get; set; }
        [Required] public string Name { get; set; }
        [Required] public string Album { get; set; }
        [Required] public string Genre { get; set; }
        [Required] public int Release_Date { get; set; }
    }
}
